schema-version = 1
release-version = "1.29.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.50.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "1.0.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "5.3.0"
vendor = "bottlerocket"
