[settings.aws]
profile = "default"

[metadata.settings.aws.config]
setting-generator = "schnauzer-v2 render --requires 'aws@v1(helpers=[aws-config])' --template '{{ aws-config settings.aws.config settings.aws.profile }}'"

[services.aws]
configuration-files = [
  "aws-config",
  "aws-credentials",
]
restart-commands = []

[metadata.settings.aws]
affected-services = ["aws"]

[configuration-files.aws-config]
path = "/root/.aws/config"
template-path = "/usr/share/templates/aws-config"

[configuration-files.aws-credentials]
path = "/root/.aws/credentials"
template-path = "/usr/share/templates/aws-credentials"
